### ISSUE TITLE
The script don't workt

### ISSUE THREAD

**Issue by Zipos75** [Jan-Bart/MMM-NMBS-Connection#1]
Hi,

I have a problem with the script in the config.js. I did install the module (with: "git clone https://github.com/Jan-Bart/MMM-NMBS-Connectionand") I did a copy paste to the example in the config.js : 
"{
  module: "MMM-NMBS-Connection",
  position: "bottom_left",
  config: {
    from: "Antwerp-Central"
    to: "Brussels-South",
    results: 3
  }
},"

but I have a problem:
![image](https://user-images.githubusercontent.com/21169473/43704692-ca49d10e-9960-11e8-90fa-49702aa1c0d2.png)

what should I do?

Thanks in advance

**Comment by Jan-Bart** [comment]
Hi Zipos75,

Is this the content of your whole `config.js` file?
Because it should be something like this:

```
var config = {
	address: "localhost", // Address to listen on, can be:
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	language: "en",
	timeFormat: 24,
	units: "metric",
	electronOptions: { fullscreen: false, width: 800, height: 600 },
	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "MMM-NMBS-Connection",
			position: "lower_third",
			config: {
				from: "Antwerp-Central",
				to: "Brussels-South",
				results: 4
			}
		}
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") { module.exports = config; }

```

If you try this as config file, does it work?

**Comment by Jan-Bart** [comment]
Hi @Zipos75 
Since I didn't hear anything from you again I'm assuming that this issue is resolved.
If you have any questions you can open a new issue and I'll be glad to help.
