### ISSUE TITLE
error in config file

### ISSUE THREAD

**Issue by bdvrieze** [Jan-Bart/MMM-NMBS-Connection#2]
Hi

First of all, thanks a *lot*. If someone would do the same for the De Lijn API ;-)

But...

I get config.js errors with the standard example...

When I add 

`{
  module: "MMM-NMBS-Connection",
  position: "bottom_left",
  config: {
    from: "Antwerp-Central"
    to: "Brussels-South",
    results: 3
  }
},`

in VS Code I already get this:

![image](https://user-images.githubusercontent.com/17237379/45738116-e5b19b00-bbef-11e8-9f6b-96a111c3014a.png)
![image](https://user-images.githubusercontent.com/17237379/45738131-f06c3000-bbef-11e8-87c3-d2f5118c033f.png)

When I use your exact code in MMM, I get the same error.

Is it me or...?

**Comment by Jan-Bart** [comment]
It's not you, it's me. 
I'm missing a `,`

It's fixed in the readme now. 
Thanks for letting me know! :)

**Comment by bdvrieze** [comment]
Comment deleted. I installed in Magic Mirror Root folder. I'm an idiot.
But I did get one catch though :)

**Comment by Jan-Bart** [comment]
😄 Yes, you did. Thx! :)
