### ISSUE TITLE
stations in French

### ISSUE THREAD

**Issue by Doudy** [Jan-Bart/MMM-NMBS-Connection#5]
Is it possible to have the names of stations in French?

![image](https://user-images.githubusercontent.com/28684288/47636918-51294980-db5a-11e8-80e2-30a7b6b6f0b9.png)

**Comment by Jan-Bart** [comment]
Hey @Doudy 

I'm sorry it took so long, but this should be available in the latest version.
By default it takes the global language but (if you want to) you can overwrite this.

<img width="139" alt="schermafbeelding 2018-11-08 om 23 09 47" src="https://user-images.githubusercontent.com/430206/48230716-44072880-e3ac-11e8-977c-7ba532221ff0.png">

**Comment by Doudy** [comment]
Thank you for the information.
But how do I do that?

**Comment by Doudy** [comment]
OK I found
I adapted language: in 'fr' in 'MMM-NMBS-Connection.js'
